server:
  port: 2550
  servlet:
    context-path: /
  undertow:
    accesslog:
      prefix: "[PAGAMENTOS-API]"

spring:
  main:
    banner-mode: 'off'
  output:
    ansi:
      enabled: 'always'
  application:
    name: 'pagamentos-api'
  cloud:
    azure:
      servicebus:
        connection-string: Endpoint=sb://servicebus-unidocs-aurora-dev-eastus-001.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=zkjJ3hkNWHUcpaUotD4VStE9vuhiGwp65Is+qkHxNHY=
#        connection-string: Endpoint=sb://dpaula.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=AGXOarbN8QxHrWhDGO3JhQHuwRS8vsUwbNEcRj0PHIc=
#    stream:
#      bindings:
#        consume-in-0:
#          destination: topic-fplima
#          group: rg-service-bus
#        supply-out-0:
#          destination: topic-fplima
#      servicebus:
#        topic:
#          bindings:
#            consume-in-0:
#              consumer:
#                checkpoint-mode: MANUAL
#
#
#      function:
#        definition: consume;supply;
#      poller:
#        fixed-delay: 1000
#        initial-delay: 0

logging:
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level %logger{1}: %msg%n'
  level:
    root: INFO
    com.dpaula: DEBUG

#ACTUATOR
management:
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: false
      prometheus:
        enabled: true
  endpoints:
    web:
      exposure:
        include: "*"

info:
  app:
    name: '@project.name@'
    description: '@project.description@'
    version: '@project.version@'
    encoding: '@project.build.sourceEncoding@'
    java:
      version: '@java.version@'
